name: CI

on: [push, pull_request]

jobs:
  container:
    runs-on: ubuntu-latest
    container: ros:melodic
    steps:
      - run: |
          apt-get update --fix-missing 
          apt-get -y install git python-pip 
          apt-get clean 

          sudo pip install -U catkin_tools
 
          cd ~/
          git clone https://github.com/dtusdc/ros.git src
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
          
          source /opt/ros/melodic/setup.bash

          catkin build
