name: ROS CI

on: [push, pull_request ]

jobs:    
  build:
    runs-on: ubuntu-18.04
    runs:
      using: 'docker'
      image: 'Dockerfile'
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          cd ~/catkin_ws
          catkin build
          source devel/setup.bash
          cd ~/catkin_ws/src
          ln -s ~/work  # $CI_SOURCE_PATH
          # echo "::warning $CI_SOURCE_PATH"
          # echo "::warning `ls -l`"
          cd ..
          catkin build
