name: CI

on: [push, pull_request]

jobs:
  container:
    runs-on: ubuntu-latest
    container: ros:melodic
    steps:
      - run: |
          docker build -t dtusdc .
          docker run -it dtusdc
          catkin build
